#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

alias atop='tmux new-window -t 9 -n atop "sudo atop"'
alias jnettop='tmux new-window -t 8 -n jnettop "sudo jnettop"'

ZSHPROFILE_RAN=yes

## Local Variables:
## mode: sh
## sh-shell: zsh
## End:
