#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export DEBEMAIL="evan@theunixman.com"
export EMAIL="evan@theunixman.com"
export DEBFULLNAME="Evan Cofsky"
export FULLNAME="Evan Cofsky"

export JAVA_OPTS="-Xmx512m -Xss256k"

typeset -aU _extra_root_paths=(
    /opt/mutt
    /opt/rocm
    /opt/amdgpu-pro
    /opt/qt59
    /projects/texmf/2017
)

function _join_paths () {
    python <<EOF
import sys
import os.path as O
paths = []
seen = set()

for l in sys.stdin:
    if not l.strip(): continue
    if l in seen(): continue
    seen.add(l)
    paths.append(l)

sys.stdout.write(O.pathsep.join(paths))
EOF
}

function _set_extra_paths () {
    local depth=4

    path=($(find ${_extra_root_paths[@]} -maxdepth $depth -type d -name 'bin') $path)

    local -Ua cmake_module_path=($(find ${_extra_root_paths[@]} -maxdepth $depth -type d ! -regex '.*/data/.*' -iname 'cmake*'))
    export CMAKE_MODULE_PATH=$(echo ${cmake_module_path[@]} | sed 's/ /:/g')${CMAKE_MODULE_PATH:+:${CMAKE_MODULE_PATH}}

    local -Ua pkg_config_path=($(find ${_extra_root_paths[@]} -maxdepth $depth -type d -iname '*pkg*conf*'))
    export PKG_CONFIG_PATH=$(echo ${pkg_config_path[@]} | sed 's/ /:/g')${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
}

path=(/home/evan/.emacs.d/term-cmd $path)

_set_extra_paths

export OPENCL_ROOT=/opt/rocm/opencl
export AMDAPPSDK=/opt/rocm/opencl

export CC=$(which clang)
export CXX=$(which clang++)

unset _set_extra_paths _extra_root_paths _join_paths

eval "$(direnv hook zsh)"
