#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Set this up for other modules.
declare -a manpath

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

for f in "${chpwd_functions[@]}"; do
    $f
done

# Customize to your needs...

if [ -f $HOME/.zprofile -a -z "$ZSHPROFILE_RAN" ]; then
    . $HOME/.zprofile
fi

# Set MANPATH
#export MANPATH="${manpath[@]}:$(manpath)"

unset ZSHPROFILE_RAN
